//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerShell.MCP.Proxy.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PromptDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PromptDescriptions() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerShell.MCP.Proxy.Resources.PromptDescriptions", typeof(PromptDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Analyze content and provide insights with actionable recommendations に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_AnalyzeContent_Description {
            get {
                return ResourceManager.GetString("Prompt_AnalyzeContent_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Analyze Content に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_AnalyzeContent_Name {
            get {
                return ResourceManager.GetString("Prompt_AnalyzeContent_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Content path and analysis requirements (e.g., &apos;C:\logs analyze errors&apos;) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_AnalyzeContent_Param_Request {
            get {
                return ResourceManager.GetString("Prompt_AnalyzeContent_Param_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create work_procedure.md and work_progress.md for project workflow management に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_CreateWorkProcedure_Description {
            get {
                return ResourceManager.GetString("Prompt_CreateWorkProcedure_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create Work Procedure に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_CreateWorkProcedure_Name {
            get {
                return ResourceManager.GetString("Prompt_CreateWorkProcedure_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Work description and directory (e.g., &apos;translate docs in C:\project&apos;) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_CreateWorkProcedure_Param_Request {
            get {
                return ResourceManager.GetString("Prompt_CreateWorkProcedure_Param_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Follow work_procedure.md and track progress in work_progress.md に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_ExecuteWorkProcedure_Description {
            get {
                return ResourceManager.GetString("Prompt_ExecuteWorkProcedure_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execute Work Procedure に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_ExecuteWorkProcedure_Name {
            get {
                return ResourceManager.GetString("Prompt_ExecuteWorkProcedure_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Working directory path (e.g., &apos;C:\project&apos;) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_ExecuteWorkProcedure_Param_Request {
            get {
                return ResourceManager.GetString("Prompt_ExecuteWorkProcedure_Param_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start fast-paced foreign language dictation training with PowerShell audio and AI evaluation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_ForeignLanguageDictationTraining_Description {
            get {
                return ResourceManager.GetString("Prompt_ForeignLanguageDictationTraining_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Foreign Language Dictation Training に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_ForeignLanguageDictationTraining_Name {
            get {
                return ResourceManager.GetString("Prompt_ForeignLanguageDictationTraining_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language and options (e.g., &apos;English fast short business&apos;) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_ForeignLanguageDictationTraining_Param_Request {
            get {
                return ResourceManager.GetString("Prompt_ForeignLanguageDictationTraining_Param_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Provide guidelines for AI to generate high-quality HTML reports with proper formatting, charts, and styling に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_HtmlGenerationGuidelinesForAi_Description {
            get {
                return ResourceManager.GetString("Prompt_HtmlGenerationGuidelinesForAi_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HTML Generation Guidelines for AI に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_HtmlGenerationGuidelinesForAi_Name {
            get {
                return ResourceManager.GetString("Prompt_HtmlGenerationGuidelinesForAi_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Learn programming languages or CLI tools interactively with hands-on practice に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_LearnProgrammingAndCli_Description {
            get {
                return ResourceManager.GetString("Prompt_LearnProgrammingAndCli_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Learn Programming &amp; CLI に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_LearnProgrammingAndCli_Name {
            get {
                return ResourceManager.GetString("Prompt_LearnProgrammingAndCli_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Technology and focus area (e.g., &apos;Python async/await&apos;) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_LearnProgrammingAndCli_Param_Request {
            get {
                return ResourceManager.GetString("Prompt_LearnProgrammingAndCli_Param_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show themed interactive maps using PowerShell.Map (best pizza spots, historic pubs, stylish cafes, etc.) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_ShowInteractiveMap_Description {
            get {
                return ResourceManager.GetString("Prompt_ShowInteractiveMap_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Interactive Map に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_ShowInteractiveMap_Name {
            get {
                return ResourceManager.GetString("Prompt_ShowInteractiveMap_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Map theme and area (e.g., &apos;Ancient Roman roads across Europe in chronological order&apos;) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_ShowInteractiveMap_Param_Request {
            get {
                return ResourceManager.GetString("Prompt_ShowInteractiveMap_Param_Request", resourceCulture);
            }
        }
    }
}
