//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerShell.MCP.Proxy.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PromptDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PromptDescriptions() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerShell.MCP.Proxy.Resources.PromptDescriptions", typeof(PromptDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        
        /// <summary>
        ///   Analyze content and provide insights with actionable recommendations に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_AnalyzeContent_Description {
            get {
                return ResourceManager.GetString("Prompt_AnalyzeContent_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Analyze Content に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_AnalyzeContent_Name {
            get {
                return ResourceManager.GetString("Prompt_AnalyzeContent_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path to content for analysis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_AnalyzeContent_Param_ContentPath {
            get {
                return ResourceManager.GetString("Prompt_AnalyzeContent_Param_ContentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create themed interactive maps using PowerShell.Map (hot springs tours, ramen maps, etc.) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_ShowInteractiveMap_Description {
            get {
                return ResourceManager.GetString("Prompt_ShowInteractiveMap_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create Interactive Map に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_ShowInteractiveMap_Name {
            get {
                return ResourceManager.GetString("Prompt_ShowInteractiveMap_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Best Pizza Spots, Historic Pubs, Stylish Cafes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_ShowInteractiveMap_Param_MapTheme {
            get {
                return ResourceManager.GetString("Prompt_ShowInteractiveMap_Param_MapTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   United States, New York, California に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_ShowInteractiveMap_Param_TargetArea {
            get {
                return ResourceManager.GetString("Prompt_ShowInteractiveMap_Param_TargetArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create work procedure and progress tracking files. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_CreateWorkProcedure_Description {
            get {
                return ResourceManager.GetString("Prompt_CreateWorkProcedure_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create Work Procedure に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_CreateWorkProcedure_Name {
            get {
                return ResourceManager.GetString("Prompt_CreateWorkProcedure_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specific focus area に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_CreateWorkProcedure_Param_FocusArea {
            get {
                return ResourceManager.GetString("Prompt_CreateWorkProcedure_Param_FocusArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Description of the work or project に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_CreateWorkProcedure_Param_WorkDescription {
            get {
                return ResourceManager.GetString("Prompt_CreateWorkProcedure_Param_WorkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Working directory to analyze に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_CreateWorkProcedure_Param_WorkingDirectory {
            get {
                return ResourceManager.GetString("Prompt_CreateWorkProcedure_Param_WorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execute work procedure and track progress with continuous improvement. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_ExecuteWorkProcedure_Description {
            get {
                return ResourceManager.GetString("Prompt_ExecuteWorkProcedure_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execute Work Procedure に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_ExecuteWorkProcedure_Name {
            get {
                return ResourceManager.GetString("Prompt_ExecuteWorkProcedure_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Working directory where work will be performed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_ExecuteWorkProcedure_Param_WorkingDirectory {
            get {
                return ResourceManager.GetString("Prompt_ExecuteWorkProcedure_Param_WorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start fast-paced foreign language dictation training with PowerShell audio and AI evaluation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_ForeignLanguageDictationTraining_Description {
            get {
                return ResourceManager.GetString("Prompt_ForeignLanguageDictationTraining_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Foreign Language Dictation Training に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_ForeignLanguageDictationTraining_Name {
            get {
                return ResourceManager.GetString("Prompt_ForeignLanguageDictationTraining_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Short (3-5 words), Medium (6-8 words), Long (9-12 words), VeryLong (13-15 words) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_ForeignLanguageDictationTraining_Param_SentenceLength {
            get {
                return ResourceManager.GetString("Prompt_ForeignLanguageDictationTraining_Param_SentenceLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show translation alongside target language (on/off) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_ForeignLanguageDictationTraining_Param_ShowTranslation {
            get {
                return ResourceManager.GetString("Prompt_ForeignLanguageDictationTraining_Param_ShowTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Slow (rate -2), Normal (rate 0), Fast (rate +2), VeryFast (rate +4) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_ForeignLanguageDictationTraining_Param_SpeechSpeed {
            get {
                return ResourceManager.GetString("Prompt_ForeignLanguageDictationTraining_Param_SpeechSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target language: English, French, German, Spanish, Italian, Chinese, Korean, Japanese に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_ForeignLanguageDictationTraining_Param_TargetLanguage {
            get {
                return ResourceManager.GetString("Prompt_ForeignLanguageDictationTraining_Param_TargetLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Airport, Business, Food, Hospital, School, Weather, Zoo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_ForeignLanguageDictationTraining_Param_Topic {
            get {
                return ResourceManager.GetString("Prompt_ForeignLanguageDictationTraining_Param_Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Guidelines for AI to generate high-quality HTML reports with proper formatting, charts, and styling に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_HtmlGenerationGuidelinesForAi_Description {
            get {
                return ResourceManager.GetString("Prompt_HtmlGenerationGuidelinesForAi_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HTML Generation Guidelines for AI に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_HtmlGenerationGuidelinesForAi_Name {
            get {
                return ResourceManager.GetString("Prompt_HtmlGenerationGuidelinesForAi_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Interactive learning for programming languages or CLI tools with hands-on practice に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_LearnProgrammingAndCli_Description {
            get {
                return ResourceManager.GetString("Prompt_LearnProgrammingAndCli_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Learn Programming & CLI に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_LearnProgrammingAndCli_Name {
            get {
                return ResourceManager.GetString("Prompt_LearnProgrammingAndCli_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   'async/await', 'branching', 'multithreading' に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_LearnProgrammingAndCli_Param_LearningFocus {
            get {
                return ResourceManager.GetString("Prompt_LearnProgrammingAndCli_Param_LearningFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Python, Git, Docker, C# に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt_LearnProgrammingAndCli_Param_Technology {
            get {
                return ResourceManager.GetString("Prompt_LearnProgrammingAndCli_Param_Technology", resourceCulture);
            }
        }
    }
}
