#
# Module manifest for module 'PowerShell.MCP'
#
# Generated by: Yoshifumi Tsuda
#
# Generated on: 2025/09/17
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PowerShell.MCP.dll'

# Version number of this module.
ModuleVersion = '1.4.1'

# Supported PSEditions
CompatiblePSEditions = @('Core')

# ID used to uniquely identify this module
GUID = '313962fa-c90b-424a-9c8a-d4a05f4a1481'

# Author of this module
Author = 'Yoshifumi Tsuda'

# Company or vendor of this module
CompanyName = 'Yoshifumi Tsuda'

# Copyright statement for this module
Copyright = '(c) Yoshifumi Tsuda. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Enables AI assistants (such as Claude Desktop) to execute PowerShell commands and CLI tools within a persistent PowerShell console. Supports Windows, Linux, and macOS.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.2'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @('PowerShell.MCP.psm1')

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @('Get-MCPProxyPath')

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @(
'Show-TextFile',
'Add-LinesToFile',
'Update-LinesInFile',
'Update-MatchInFile',
'Remove-LinesFromFile'
)

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'MCP','AI','Assistant','PowerShell','Automation','Enterprise','Windows','Linux','macOS','Cross-Platform'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/yotsuda/PowerShell.MCP/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/yotsuda/PowerShell.MCP'

        # A URL to an icon representing this module.
        # IconUri = ''

        Platforms = @('Windows', 'Linux', 'macOS')

        # ReleaseNotes of this module
        ReleaseNotes = 'PowerShell.MCP v1.4.1 - Cross-Platform MCP Server

=== Cross-Platform Support ===
Now available on Windows, Linux, and macOS!
• Windows: x64
• Linux: x64 (gnome-terminal, konsole, xfce4-terminal, xterm, and more)
• macOS: x64 (Intel), arm64 (Apple Silicon)

=== Key Features ===
• 🤝 Shared Console Experience
• 🔄 Persistent Session State
• ⚡ Instant Response, Zero Overhead
• 🔍 Comprehensive Output Stream Capture
• 📝 LLM-Optimized Text File Operations
• 🔗 PowerShell Pipeline Composability
• 🌐 Universal Modules & CLI Tools Integration
• 📚 No RAG or Context Grounding Required
• 🎯 Ready-to-Use Built-in Prompts
• 🔐 Enterprise-Ready Security

=== First-Time Demo ===
• "Show what PowerShell.MCP can do in a colorful, dynamic, and fun demo"
• "Try out different styles of notifications using the BurntToast module"
• "Automate Notepad: type text and smoothly move the window in a circle"
• "Tell me how to use Git in PowerShell"
• "How does it feel now that you have a tool like PowerShell.MCP?"

=== Popular Examples ===
• "Review git changes and suggest a commit message"
• "Generate system performance HTML report and open in browser"
• "Show processes consuming more than 100MB memory, sorted by CPU usage"
• "Create colorful disk usage analysis charts and visualizations"
• "Export installed programs to CSV and open in Excel"
• "Review code files and generate development documentation"

=== Quick Setup (Windows) ===
1. Install PowerShell 7.2+
2. Install-Module PowerShell.MCP
3. Get proxy path: Get-MCPProxyPath -Escape
4. Add to Claude Desktop config (%APPDATA%\Claude\claude_desktop_config.json):
   {
     "mcpServers": {
       "PowerShell": {
         "command": "C:\\Users\\YourName\\...\\PowerShell.MCP.Proxy.exe"
       }
     }
   }
   Replace "command" value with output from step 3.
5. Restart Claude Desktop

=== Quick Setup (Linux / macOS) ===
1. Install PowerShell 7.2+
2. pwsh -Command "Install-Module PowerShell.MCP -Scope CurrentUser -Force"
3. chmod +x $(pwsh -Command "Import-Module PowerShell.MCP; Get-MCPProxyPath")
4. Get proxy path: Get-MCPProxyPath
5. Add to Claude Desktop config (~/.config/Claude/claude_desktop_config.json):
   {
     "mcpServers": {
       "PowerShell": {
         "command": "/home/yourname/.local/.../PowerShell.MCP.Proxy"
       }
     }
   }
   Replace "command" value with output from step 4.
6. Restart Claude Desktop

=== Requirements ===
PowerShell 7.2+, PSReadLine 2.3.4+ (Windows only, auto-loaded)

=== Documentation ===
Full examples & setup guide: https://github.com/yotsuda/PowerShell.MCP#examples
Security policy: https://github.com/yotsuda/PowerShell.MCP/blob/main/SECURITY.md

⚠  Provides complete PowerShell access. Use in trusted environments only.
'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'https://github.com/yotsuda/PowerShell.MCP#readme'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
